# Production docker-compose configuration
services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - webnet
    expose:
      - '3000'

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/facturation_frontend/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/facturation_frontend/nginx/certs:/etc/ssl/certs:ro
    depends_on:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
