declare namespace NodeJS {
	interface ProcessEnv {
		// Urls prefix
		DEBUG_MODE: string;
		NEXT_PUBLIC_HTTP_PROTOCOLE: 'http' | 'https';
		HTTP: string;
		WS: string;
		// Next.js backend api (for cookies)
		NEXT_PUBLIC_BACKEND_DOMAIN: string;
		NEXT_PUBLIC_BACKEND_API: string;
		NEXT_PUBLIC_API_ROOT_URL: string;
		NEXT_PUBLIC_API_ROOT_PORT: string;
		NEXT_PUBLIC_API_URL: string;
		// Base urls
		NEXT_PUBLIC_ROOT_API_URL: string;
		NEXT_PUBLIC_ROOT_WS_URL: string;
		AUTH_TRUST_HOST: string;
		NEXTAUTH_SECRET: string;
		NEXTAUTH_URL: string;
		NEXT_PUBLIC_DOMAIN_URL_PREFIX: string;
		// Account
		NEXT_PUBLIC_ACCOUNT_ROOT: string;
		NEXT_PUBLIC_ACCOUNT_REFRESH_TOKEN: string;
		NEXT_PUBLIC_ACCOUNT_LOGIN: string;
		NEXT_PUBLIC_ACCOUNT_LOGOUT: string;
		NEXT_PUBLIC_ACCOUNT_CREATE_ACCOUNT: string;
		NEXT_PUBLIC_ACCOUNT_CHECK_EMAIL: string;
		NEXT_PUBLIC_ACCOUNT_PASSWORD_CHANGE: string;
		NEXT_PUBLIC_ACCOUNT_SEND_PASSWORD_RESET: string;
		NEXT_PUBLIC_ACCOUNT_PASSWORD_RESET: string;
		NEXT_PUBLIC_ACCOUNT_PROFIL: string;
		NEXT_PUBLIC_ACCOUNT_GROUPS: string;
		NEXT_PUBLIC_USERS_ROOT: string;
		// Company
		NEXT_PUBLIC_COMPANY_ROOT: string;
		NEXT_PUBLIC_COMPANY_LIST: string;
		NEXT_PUBLIC_USER_COMPANIES_LIST: string;
		// Client
		NEXT_PUBLIC_CLIENT_ROOT: string;
		NEXT_PUBLIC_CLIENT_LIST: string;
		NEXT_PUBLIC_CLIENT_GENERATE_CODE_CLIENT: string;
		NEXT_PUBLIC_ARCHIVE_CLIENT: string;
		// Article
		NEXT_PUBLIC_ARTICLE_ROOT: string;
		NEXT_PUBLIC_ARTICLE_LIST: string;
		NEXT_PUBLIC_ARTICLE_GENERATE_CODE_REFERENCE: string;
		NEXT_PUBLIC_ARCHIVE_ARTICLE: string;
		// Devis
		NEXT_PUBLIC_DEVIS_ROOT: string;
		NEXT_PUBLIC_DEVIS_LIST: string;
		NEXT_PUBLIC_DEVIS_GENERATE_NUM_DEVIS: string;
		NEXT_PUBLIC_DEVIS_SWITCH_STATUT: string;
		NEXT_PUBLIC_DEVIS_CONVERT_TO_FACTURE_PRO_FORMA: string;
		NEXT_PUBLIC_DEVIS_CONVERT_TO_FACTURE_CLIENT: string;
		NEXT_PUBLIC_DEVIS_PDF: string;
		// Facture Pro Forma
		NEXT_PUBLIC_FACTURE_PROFORMA_ROOT: string;
		NEXT_PUBLIC_FACTURE_PROFORMA_LIST: string;
		NEXT_PUBLIC_FACTURE_PROFORMA_GENERATE_NUM_FACTURE: string;
		NEXT_PUBLIC_FACTURE_PROFORMA_SWITCH_STATUT: string;
		NEXT_PUBLIC_FACTURE_PROFORMAT_CONVERT_TO_FACTURE_CLIENT: string;
		NEXT_PUBLIC_FACTURE_PROFORMA_PDF: string;
		// Facture Client
		NEXT_PUBLIC_FACTURE_CLIENT_ROOT: string;
		NEXT_PUBLIC_FACTURE_CLIENT_LIST: string;
		NEXT_PUBLIC_FACTURE_CLIENT_UNPAID: string;
		NEXT_PUBLIC_FACTURE_CLIENT_FOR_PAYMENT: string;
		NEXT_PUBLIC_FACTURE_CLIENT_GENERATE_NUM_FACTURE: string;
		NEXT_PUBLIC_FACTURE_CLIENT_SWITCH_STATUT: string;
		NEXT_PUBLIC_FACTURE_CLIENT_CONVERT_TO_BON_DE_LIVRAISON: string;
		NEXT_PUBLIC_FACTURE_CLIENT_PDF: string;
		// Bon de Livraison
		NEXT_PUBLIC_BON_DE_LIVRAISON_ROOT: string;
		NEXT_PUBLIC_BON_DE_LIVRAISON_LIST: string;
		NEXT_PUBLIC_BON_DE_LIVRAISON_UNINVOICED: string;
		NEXT_PUBLIC_BON_DE_LIVRAISON_GENERATE_NUM_BON_DE_LIVRAISON: string;
		NEXT_PUBLIC_BON_DE_LIVRAISON_SWITCH_STATUT: string;
		NEXT_PUBLIC_BON_DE_LIVRAISON_PDF: string;
		// Reglement
		NEXT_PUBLIC_REGLEMENT_ROOT: string;
		NEXT_PUBLIC_REGLEMENT_LIST: string;
		NEXT_PUBLIC_REGLEMENT_SWITCH_STATUT: string;
		NEXT_PUBLIC_REGLEMENT_PDF: string;
		// Parameter
		NEXT_PUBLIC_PARAMETER_ROOT: string;
		NEXT_PUBLIC_PARAMETER_VILLE: string;
		NEXT_PUBLIC_PARAMETER_MARQUE: string;
		NEXT_PUBLIC_PARAMETER_CATEGORIE: string;
		NEXT_PUBLIC_PARAMETER_UNITE: string;
		NEXT_PUBLIC_PARAMETER_EMPLACEMENT: string;
		NEXT_PUBLIC_PARAMETER_MODE_PAIEMENT: string;
		NEXT_PUBLIC_PARAMETER_MODE_REGLEMENT: string;
		NEXT_PUBLIC_PARAMETER_LIVRE_PAR: string;
	}
}
