// Initialise the APP
export const INIT_APP = 'INIT_APP';
export const INIT_APP_SESSION_TOKENS = 'INIT_APP_SESSION_TOKENS';
export const REFRESH_APP_TOKEN_STATES = 'REFRESH_APP_TOKEN_STATES';
// Account
export const ACCOUNT_POST_RESEND_VERIFICATION = 'ACCOUNT_POST_RESEND_VERIFICATION';
export const ACCOUNT_POST_PASSWORD_CHANGE = 'ACCOUNT_POST_PASSWORD_CHANGE';
export const ACCOUNT_POST_SEND_PASSWORD_RESET = 'ACCOUNT_POST_SEND_PASSWORD_RESET';
export const ACCOUNT_PATCH_PROFIL = 'ACCOUNT_PATCH_PROFIL';
export const ACCOUNT_GET_CHECK_ACCOUNT = 'ACCOUNT_GET_CHECK_ACCOUNT';
// WS Events
export const WS_USER_AVATAR = 'WS_USER_AVATAR';
