// Initialise the APP
export const INIT_APP = 'INIT_APP';
export const INIT_APP_SESSION_TOKENS = 'INIT_APP_SESSION_TOKENS';
export const REFRESH_APP_TOKEN_STATES = 'REFRESH_APP_TOKEN_STATES';
export const ACCOUNT_POST_LOGIN = 'ACCOUNT_POST_LOGIN';