export type Language = 'fr' | 'en';

export type TranslationDictionary = {
	common: {
		yes: string;
		no: string;
		save: string;
		cancel: string;
		delete: string;
		edit: string;
		view: string;
		actions: string;
		add: string;
		back: string;
		update: string;
		confirm: string;
		search: string;
		loading: string;
		refresh: string;
		retry: string;
		submit: string;
		close: string;
		display: string;
		displayPdf: string;
		selectValue: string;
		filterBy: string;
		dashboard: string;
		skipToContent: string;
		noResults: string;
		allStatuses: string;
		newItem: string;
		archive: string;
		unarchive: string;
		archived: string;
		suspend: string;
		reset: string;
		devise: string;
		validationErrors: string;
		correctErrors: string;
		irreversible: string;
		dateCreation: string;
		dateMaj: string;
		allTypes: string;
		seeMore: string;
		pdf: string;
		pdfWithDiscount: string;
		pdfWithoutDiscount: string;
		pdfWithUnit: string;
		pdfNormal: string;
		pdfQuantityOnly: string;
		convert: string;
		print: string;
		configure: string;
		noData: string;
		validShort: string;
		cancelledShort: string;
		value: string;
		noOptions: string;
		addFilter: string;
		clearAllFilters: string;
		genericError: string;
		addImage: string;
		clickToEditCrop: string;
		croppedPreview: string;
		pdfUnit: string;
		togglePasswordVisibility: string;
		avatarPreview: string;
		editPhoto: string;
		toggleDrawer: string;
		moreActions: string;
		companiesTabs: string;
		refreshPage: string;
	};
	navigation: {
		dashboard: string;
		viewDashboard: string;
		articles: string;
		articlesList: string;
		articlesArchived: string;
		clients: string;
		clientsList: string;
		clientsArchived: string;
		devis: string;
		devisList: string;
		facturesProforma: string;
		facturesProformaList: string;
		facturesClient: string;
		facturesClientList: string;
		facturesImpayees: string;
		bonsLivraison: string;
		bonsLivraisonList: string;
		bonsLivraisonUninvoiced: string;
		reglement: string;
		reglementsList: string;
		companies: string;
		companiesList: string;
		newCompany: string;
		users: string;
		usersList: string;
		newUser: string;
		settings: string;
		myProfile: string;
		changePassword: string;
		monthlyObjectives: string;
		configureMonthlyObjectives: string;
		logout: string;
		administration: string;
		welcomeMale: string;
		welcomeFemale: string;
		welcomeNeutral: string;
	};
	validation: {
		required: string;
		shortRequired: string;
		tvaInvalid: string;
		percentageInvalid: string;
		minLength: (n: number) => string;
		maxLength: (n: number) => string;
		phoneFormat: string;
		emailInvalid: string;
		passwordMinLength: (n: number) => string;
		quantityInteger: string;
		priceVenteAchat: string;
		urlInvalid: string;
		remisePourcentage: string;
		remiseFix: string;
		yearPartInvalid: string;
	};
	errors: {
		errorOccurred: string;
		errorApology: string;
		errorOccurredMessage: string;
		authRequired: string;
		documentOpenError: string;
		pageNotFound: string;
		pageNotFoundText: string;
		accessDenied: string;
		accessDeniedText: string;
		maintenanceTitle: string;
		maintenanceText: string;
		maintenanceSuspended: string;
		maintenanceThanks: string;
		deletionError: string;
		serverError: string;
		networkError: string;
	};
	pdf: {
		generatePdf: string;
		chooseLanguage: string;
		french: string;
		english: string;
	};
	rawData: {
		genders: {
			male: string;
			female: string;
		};
		employeeRanges: {
			'1to5': string;
			'5to10': string;
			'10to50': string;
			'50to100': string;
			moreThan100: string;
		};
		civilites: {
			mr: string;
			mrs: string;
			miss: string;
		};
		documentStatuses: {
			draft: string;
			sent: string;
			accepted: string;
			refused: string;
			cancelled: string;
			expired: string;
			invoiced: string;
		};
		remiseTypes: {
			percentage: string;
			fixed: string;
		};
	};
	shared: {
		sessionExpired: string;
		noPermission: string;
		noPermissionText: string;
		selectAllPage: (n: number) => string;
		selectAllMatching: (n: number) => string;
		allMatchingSelected: (n: number) => string;
		clearSelection: string;
		loadingIds: string;
		noManager: string;
		noCompanyAssigned: string;
		companyHeader: string;
		roleHeader: string;
		addCompany: string;
		addUser: string;
		selectCompany: string;
		selectUser: string;
		selectRole: string;
		role: string;
		selectionError: string;
		noCompaniesFound: string;
		noCompaniesAdminMessage: string;
		createCompany: string;
		noCompaniesUserMessage: string;
	};
	articles: {
		listTitle: string;
		archivedTitle: string;
		detailsTitle: string;
		backToList: string;
		newArticle: string;
		addTitle: string;
		navAddTitle: string;
		editTitle: string;
		photoSection: string;
		identitySection: string;
		pricesSection: string;
		classificationSection: string;
		remarkSection: string;
		datesSection: string;
		colPhoto: string;
		colReference: string;
		colType: string;
		colDesignation: string;
		colPrixAchat: string;
		colPrixVente: string;
		colDateCreation: string;
		filterCategorie: string;
		filterEmplacement: string;
		filterUnite: string;
		filterMarque: string;
		typeProduit: string;
		typeService: string;
		allTypes: string;
		fieldReference: string;
		fieldDesignation: string;
		fieldPrixAchat: string;
		fieldPrixVente: string;
		fieldTva: string;
		fieldCategorie: string;
		fieldEmplacement: string;
		fieldUnite: string;
		fieldMarque: string;
		fieldRemarque: string;
		fieldPhoto: string;
		fieldPhotoCropped: string;
		noCategorie: string;
		noEmplacement: string;
		noUnite: string;
		noMarque: string;
		resetReference: string;
		importTooltip: string;
		emailTooltip: string;
		importErrorsTitle: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		archiveSuccess: string;
		archiveError: string;
		unarchiveSuccess: string;
		unarchiveError: string;
		importSuccess: (n: number) => string;
		importError: string;
		emailSuccess: string;
		emailError: string;
		bulkDeleteSuccess: (n: number) => string;
		bulkDeleteError: string;
		bulkArchiveSuccess: (n: number) => string;
		bulkArchiveError: string;
		bulkUnarchiveSuccess: (n: number) => string;
		bulkUnarchiveError: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		archiveModalTitle: string;
		archiveModalBody: string;
		unarchiveModalTitle: string;
		unarchiveModalBody: string;
		bulkDeleteModalTitle: (n: number) => string;
		bulkDeleteModalBody: (n: number) => string;
		bulkArchiveModalTitle: (n: number) => string;
		bulkArchiveModalBody: (n: number) => string;
		bulkUnarchiveModalTitle: (n: number) => string;
		bulkUnarchiveModalBody: (n: number) => string;
		bulkDeleteBtn: (n: number) => string;
		bulkArchiveBtn: (n: number) => string;
		bulkUnarchiveBtn: (n: number) => string;
	};
	clients: {
		listTitle: string;
		archivedTitle: string;
		detailsTitle: string;
		backToList: string;
		newClient: string;
		addTitle: string;
		editTitle: string;
		typeSection: string;
		identitySection: string;
		contactSection: string;
		adminSection: string;
		villeSection: string;
		remarkSection: string;
		datesSection: string;
		colCodeClient: string;
		colType: string;
		colRaisonSociale: string;
		colNom: string;
		colPrenom: string;
		colVille: string;
		colDateCreation: string;
		filterVille: string;
		typePersonneMorale: string;
		typePersonnePhysique: string;
		allTypes: string;
		allVilles: string;
		fieldCodeClient: string;
		fieldRaisonSociale: string;
		fieldNom: string;
		fieldPrenom: string;
		fieldAdresse: string;
		fieldEmail: string;
		fieldTelephone: string;
		fieldNumeroCompte: string;
		fieldICE: string;
		fieldRegistreCommerce: string;
		fieldIdentifiantFiscal: string;
		fieldTaxeProfessionnelle: string;
		fieldCNSS: string;
		fieldVille: string;
		fieldDelaiPaiement: string;
		fieldRemarque: string;
		noVille: string;
		resetCode: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		archiveSuccess: string;
		archiveError: string;
		unarchiveSuccess: string;
		unarchiveError: string;
		bulkDeleteSuccess: (n: number) => string;
		bulkDeleteError: string;
		bulkArchiveSuccess: (n: number) => string;
		bulkArchiveError: string;
		bulkUnarchiveSuccess: (n: number) => string;
		bulkUnarchiveError: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		archiveModalTitle: string;
		archiveModalBody: string;
		unarchiveModalTitle: string;
		unarchiveModalBody: string;
		bulkDeleteModalTitle: (n: number) => string;
		bulkDeleteModalBody: (n: number) => string;
		bulkArchiveModalTitle: (n: number) => string;
		bulkArchiveModalBody: (n: number) => string;
		bulkUnarchiveModalTitle: (n: number) => string;
		bulkUnarchiveModalBody: (n: number) => string;
		bulkDeleteBtn: (n: number) => string;
		bulkArchiveBtn: (n: number) => string;
		bulkUnarchiveBtn: (n: number) => string;
	};
	devis: {
		listTitle: string;
		detailsTitle: string;
		backToList: string;
		newDevis: string;
		addTitle: string;
		editTitle: string;
		colNumeroDevis: string;
		colDateDevis: string;
		colNumeroDemandePrix: string;
		filterModePaiement: string;
		fieldNumeroDemandePrix: string;
		fieldDate: string;
		fieldStatut: string;
		linesTitle: string;
		statusTitle: string;
		documentNumberLabel: string;
		documentDateLabel: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		deleteLineBody: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		convertToProformaTitle: string;
		convertToProformaBody: string;
		convertToFactureTitle: string;
		convertToFactureBody: string;
		labelFactureProforma: string;
		labelFactureClient: string;
	};
	facturesProforma: {
		listTitle: string;
		detailsTitle: string;
		backToList: string;
		newFacture: string;
		addTitle: string;
		editTitle: string;
		colNumeroFacture: string;
		colDateFacture: string;
		colNumeroBonCommande: string;
		filterModePaiement: string;
		fieldNumeroBonCommande: string;
		fieldDate: string;
		fieldStatut: string;
		linesTitle: string;
		statusTitle: string;
		documentNumberLabel: string;
		documentDateLabel: string;
		termsSecondLabel: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		deleteLineBody: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		convertToFactureTitle: string;
		convertToFactureBody: string;
		labelFactureClient: string;
	};
	facturesClient: {
		listTitle: string;
		unpaidListTitle: string;
		detailsTitle: string;
		backToList: string;
		newFacture: string;
		addTitle: string;
		editTitle: string;
		colNumeroFacture: string;
		colDateFacture: string;
		colNumeroBonCommande: string;
		filterModePaiement: string;
		fieldNumeroBonCommande: string;
		fieldDate: string;
		fieldStatut: string;
		linesTitle: string;
		statusTitle: string;
		documentNumberLabel: string;
		documentDateLabel: string;
		termsSecondLabel: string;
		statsCA: string;
		statsReglements: string;
		statsImpayes: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		deleteLineBody: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		convertToBLTitle: string;
		convertToBLBody: string;
		labelBonLivraison: string;
	};
	bonsLivraison: {
		listTitle: string;
		uninvoicedTitle: string;
		detailsTitle: string;
		backToList: string;
		backToListBL: string;
		newBL: string;
		addTitle: string;
		editTitle: string;
		colNumeroBL: string;
		colDateBL: string;
		colNumeroBonCommande: string;
		filterModePaiement: string;
		filterLivrePar: string;
		fieldNumeroBonCommande: string;
		fieldDate: string;
		fieldStatut: string;
		linesTitle: string;
		statusTitle: string;
		documentNumberLabel: string;
		documentDateLabel: string;
		termsSecondLabel: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		deleteLineBody: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		documentTypeName: string;
	};
	reglements: {
		listTitle: string;
		detailsTitle: string;
		backToList: string;
		newReglement: string;
		addTitle: string;
		editTitle: string;
		colNumeroFacture: string;
		colClient: string;
		colModeReglement: string;
		colMontant: string;
		colDateReglement: string;
		colDateEcheance: string;
		colStatut: string;
		filterModeReglement: string;
		statusValide: string;
		statusAnnule: string;
		allStatuts: string;
		fieldFactureClient: string;
		fieldModeReglement: string;
		fieldMontant: string;
		fieldLibelle: string;
		fieldDateReglement: string;
		fieldDateEcheance: string;
		noFacture: string;
		noModeReglement: string;
		selectFacture: string;
		montantFacture: string;
		totalReglements: string;
		resteAPayer: string;
		ceReglement: string;
		infoFinancieres: string;
		infoFacture: string;
		detailsReglement: string;
		statusSection: string;
		montantDeFacture: string;
		labelClient: string;
		maxLabel: (n: string) => string;
		helpSelectFacture: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		cancelSuccess: string;
		cancelError: string;
		bulkDeleteSuccess: (n: number) => string;
		bulkDeleteError: string;
		bulkDeleteBtn: (n: number) => string;
		bulkDeleteModalTitle: (n: number) => string;
		bulkDeleteModalBody: (n: number) => string;
		deleteModalTitle: string;
		deleteModalBody: string;
		cancelModalTitle: string;
		cancelModalBody: string;
		cancelBtn: string;
		printBtn: string;
		printReceipt: string;
		labelFactureClient: string;
		statsCA: string;
		statsImpayes: string;
	};
	companies: {
		listTitle: string;
		detailsTitle: string;
		backToList: string;
		newCompany: string;
		addTitle: string;
		editTitle: string;
		colLogo: string;
		colRaisonSociale: string;
		colICE: string;
		colResponsable: string;
		colEmail: string;
		colTelephone: string;
		colEmployes: string;
		colDateCreation: string;
		logoSection: string;
		generalSection: string;
		adminSection: string;
		responsableSection: string;
		contactSection: string;
		managersSection: string;
		stampSection: string;
		settingsSection: string;
		logoLabel: string;
		stampLabel: string;
		fieldRaisonSociale: string;
		fieldEmail: string;
		fieldNbrEmploye: string;
		fieldAdresse: string;
		fieldSiteWeb: string;
		fieldNumeroCompte: string;
		fieldICE: string;
		fieldRegistreCommerce: string;
		fieldIdentifiantFiscal: string;
		fieldTaxeProfessionnelle: string;
		fieldCNSS: string;
		fieldCivilite: string;
		fieldNomResponsable: string;
		fieldGsmResponsable: string;
		fieldTelephone: string;
		fieldFax: string;
		fieldDateCreation: string;
		fieldDateMaj: string;
		fieldNombreEmployes: string;
		fieldSitewebLabel: string;
		noManager: string;
		companyNameFallback: string;
		companyChip: string;
		suspendSuccess: string;
		suspendError: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		bulkSuspendSuccess: (n: number) => string;
		bulkSuspendError: string;
		suspendModalTitle: string;
		suspendModalBody: string;
		bulkSuspendModalTitle: (n: number) => string;
		bulkSuspendModalBody: (n: number) => string;
		suspendBtn: string;
		bulkSuspendBtn: (n: number) => string;
		foreignCurrencyLabel: string;
		foreignCurrencyHelper: string;
		fetchIdsError: string;
		allEmployeeCounts: string;
	};
	users: {
		listTitle: string;
		detailsTitle: string;
		backToList: string;
		newUser: string;
		addTitle: string;
		editTitle: string;
		generalInfoSection: string;
		colAvatar: string;
		colNom: string;
		colPrenom: string;
		colEmail: string;
		colSexe: string;
		colAdmin: string;
		colActive: string;
		colDateInscription: string;
		colDerniereConnexion: string;
		photoSection: string;
		personalSection: string;
		accountSection: string;
		companiesSection: string;
		fieldEmail: string;
		fieldNom: string;
		fieldPrenom: string;
		fieldSexe: string;
		fieldIsActive: string;
		fieldIsStaff: string;
		fieldCompanies: string;
		fieldAvatar: string;
		fieldAvatarCropped: string;
		isActiveLabel: string;
		isAdminLabel: string;
		filterSexeHomme: string;
		filterSexeFemme: string;
		filterBothSexes: string;
		filterBothValues: string;
		filterOui: string;
		filterNon: string;
		adminChip: string;
		activeChip: string;
		inactiveChip: string;
		companiesCount: (n: number) => string;
		noCompany: string;
		userFallback: (id: number) => string;
		emailFallback: string;
		addSuccess: string;
		addError: string;
		updateSuccess: string;
		updateError: string;
		deleteSuccess: string;
		deleteError: string;
		bulkDeleteSuccess: (n: number) => string;
		bulkDeleteError: string;
		deleteModalTitle: string;
		deleteModalBody: string;
		bulkDeleteModalTitle: (n: number) => string;
		bulkDeleteModalBody: (n: number) => string;
		bulkDeleteBtn: (n: number) => string;
	};
	settings: {
		profileTitle: string;
		passwordTitle: string;
		navbarTitle: string;
		fieldEmail: string;
		fieldNom: string;
		fieldPrenom: string;
		fieldGenre: string;
		fieldOldPassword: string;
		fieldNewPassword: string;
		fieldConfirmPassword: string;
		updateBtn: string;
		changePasswordBtn: string;
		defaultPasswordWarning: string;
		profileUpdateSuccess: string;
		profileUpdateError: string;
		passwordChangeSuccess: string;
		passwordChangeError: string;
	};
	dashboard: {
		sectionKpi: string;
		sectionObjectifs: string;
		sectionFinancier: string;
		sectionCommercial: string;
		sectionOperationnel: string;
		sectionTresorerie: string;
		sectionClients: string;
		sectionRemises: string;
		sectionGlobal: string;
		kpiCA: string;
		kpiCreances: string;
		kpiMoyenneFacture: string;
		kpiClientsActifs: string;
		kpiCATooltip: string;
		kpiCreancesTooltip: string;
		kpiMoyenneTooltip: string;
		kpiClientsTooltip: string;
		noKpi: string;
		noObjectifs: string;
		objectifsNotSet: string;
		configureObjectifs: string;
		objectifCA: (devise: string) => string;
		objectifFactures: string;
		objectifConversion: string;
		objectifCATooltip: string;
		objectifFacturesTooltip: string;
		objectifConversionTooltip: string;
		percentAtteint: (n: string) => string;
		dateFrom: string;
		dateTo: string;
		resetDates: string;
		chartCA: string;
		chartCADesc: string;
		chartRepartitionCA: string;
		chartRepartitionCADesc: string;
		chartPaiements: string;
		chartPaiementsDesc: string;
		chartRecouvrement: string;
		chartRecouvrementDesc: string;
		chartTopClients: string;
		chartTopClientsDesc: string;
		chartTopProduits: string;
		chartTopProduitsDesc: string;
		chartTauxConversion: string;
		chartTauxConversionDesc: string;
		chartPrixVolume: string;
		chartPrixVolumeDesc: string;
		chartRepartitionFactures: string;
		chartRepartitionFacturesDesc: string;
		chartVolumeDocuments: string;
		chartVolumeDocumentsDesc: string;
		chartChronologie: string;
		chartChronologieDesc: string;
		chartCreances: string;
		chartCreancesDesc: string;
		chartDelaiPaiement: string;
		chartDelaiPaiementDesc: string;
		chartMeilleursClient: string;
		chartMeilleursClientDesc: string;
		chartRemises: string;
		chartRemisesDesc: string;
		chartMarges: string;
		chartMargesDesc: string;
		chartComparaison: string;
		chartComparaisonDesc: string;
		chartTendances: string;
		chartTendancesDesc: string;
		noRevenue: string;
		noRepartition: string;
		noPaiement: string;
		noEncaissement: string;
		noClient: string;
		noProduit: string;
		noDevis: string;
		noProduitData: string;
		noFacture: string;
		noDocument: string;
		noPaiementData: string;
		noCreance: string;
		noDelai: string;
		noClientProfile: string;
		noRemise: string;
		noMarge: string;
		noPerformance: string;
		noTendances: string;
		factureLabel: (devise: string) => string;
		caLabel: (devise: string) => string;
		encaisseLabel: (devise: string) => string;
		montantLabel: (devise: string) => string;
		qteLabel: string;
		prixMoyLabel: (devise: string) => string;
		margeLabel: (devise: string) => string;
		delaiLabel: string;
		factures: string;
		devis: string;
		bls: string;
		moisEnCours: string;
		moisPrecedent: string;
		encaisse: string;
		restant: string;
		atteint: string;
		facture: string;
		collected: string;
		noName: string;
		demoTitle: string;
		dummyDataBadge: string;
		scenarioLabel: string;
		scenarioLow: string;
		scenarioNormal: string;
		scenarioHigh: string;
		tauxRecouvrement: string;
		trendFinancier: string;
		trendCommercial: string;
		trendOperationnel: string;
		trendTresorerie: string;
		// Additional dashboard keys
		defaultEmpty: string;
		noData: string;
		mainTitle: string;
		noClientFound: string;
		noProduitFound: string;
		noDevisFound: string;
		noDocumentFound: string;
		noFactureFound: string;
		noCreanceData: string;
		noKpiData: string;
		noObjectifsData: string;
		facture2: string;
		montantTTC: (devise: string) => string;
		remiseDevise: (devise: string) => string;
		margeMoyLabel: (devise: string) => string;
		factureDevise: (devise: string) => string;
		prixLabel: (devise: string) => string;
		quantiteAxis: string;
		chartMicroTendances: string;
		chartMicroTendancesDesc: string;
		metricVolume: string;
		metricFrequence: string;
		metricMontantMoy: string;
		metricRapidite: string;
		metricAcceptRate: string;
		metricCA10k: string;
		metricDevis2: string;
		metricConversion: string;
		metricEncaisse10k: string;
		metricNouvClients: string;
		tooltipEvolutionCA: string;
		tooltipRepartitionCA: string;
		tooltipPaiements: string;
		tooltipRecouvrement: string;
		tooltipTopClients: string;
		tooltipTopProduits: string;
		tooltipConversion: string;
		tooltipPrixVolume: string;
		tooltipRepartitionFactures: string;
		tooltipVolumeDocuments: string;
		tooltipChronologie: string;
		tooltipCreances: string;
		tooltipDelaiPaiement: string;
		tooltipMeilleursClient: string;
		tooltipRemises: string;
		tooltipMarges: string;
		tooltipComparaison: string;
		tooltipMicroTendances: string;
		// Dummy-specific labels
		montantMAD: string;
		prixHTMAD: string;
		prixMAD: string;
		montantTotalMAD: string;
		remiseMAD: string;
		montantAxisMAD: string;
		margePercent: string;
		encaissementsX10k: string;
		nouveauxClients: string;
		objectifCA2: string;
	};
	documentForm: {
		deleteLineTitle: string;
		deleteLineBody: string;
		modePaiementLabel: string;
		livreurLabel: string;
		noArticlesError: string;
		statusUpdateSuccess: string;
		statusUpdateError: string;
		documentInfoSection: string;
		fieldNumero: string;
		fieldAnnee: string;
		resetNumero: string;
		clientSection: string;
		noClientFound: string;
		selectClient: string;
		deviseSection: string;
		deviseLabel: string;
		deviseMAD: string;
		deviseEUR: string;
		deviseUSD: string;
		deviseLockedHelper: string;
		deviseHelper: string;
		paymentSection: string;
		noModePaiement: string;
		noLivreurFound: string;
		livrePar: string;
		remiseGlobaleSection: string;
		applyGlobalRemise: string;
		removeGlobalRemise: string;
		remiseApplied: string;
		remarqueSection: string;
		remarqueLabel: string;
		addArticlesBtn: string;
		addArticleBtn: string;
		colPhoto: string;
		colReference: string;
		colDesignation: string;
		colMarque: string;
		colCategorie: string;
		colPrixAchat: string;
		colPrixVente: string;
		colQuantite: string;
		colTypeRemise: string;
		colRemise: string;
		colActions: string;
		deleteLineAriaLabel: string;
		fieldNumeroLabel: string;
		fieldAnneeLabel: string;
		fieldClientLabel: string;
		fieldDateLabel: string;
		fieldDemandePrixLabel: string;
		fieldBonCommandeLabel: string;
		fieldModePaiementLabel: string;
		fieldLivreurLabel: string;
		fieldRemarqueLabel: string;
		fieldTypeRemiseLabel: string;
		fieldRemiseLabel: string;
		fieldRemiseGlobaleLabel: string;
		fieldLignesLabel: string;
		fieldArticlesLabel: string;
		fieldPrixVenteLabel: string;
		fieldPrixAchatLabel: string;
		fieldQuantiteLabel: string;
		fieldDesignationLabel: string;
		fieldReferenceLabel: string;
		fieldMarqueLabel: string;
		fieldCategorieLabel: string;
		fieldGlobalErrorLabel: string;
		fieldStatut: string;
	};
	documentList: {
		bulkDeleteSuccess: (n: number, type: string) => string;
		bulkDeleteError: string;
		bulkDeletePartialError: (n: number) => string;
		convertSuccess: (type: string) => string;
		convertError: (type: string) => string;
		authError: string;
		bulkDeleteBtn: (n: number) => string;
		colClient: string;
		allClients: string;
		colStatut: string;
		colTotalTTC: string;
		colNombreArticles: string;
		bulkDeleteTitle: (n: number) => string;
		bulkDeleteBody: (n: number, type: string) => string;
	};
	documentView: {
		documentInfoSection: string;
		clientSection: string;
		clientLabel: string;
		paymentSection: string;
		modePaiementLabel: string;
		livreParLabel: string;
		remiseGlobaleSection: string;
		remiseAppliedLabel: string;
		remarqueSection: string;
		remarqueLabel: string;
		systemInfoSection: string;
		createdByLabel: string;
		colPhoto: string;
		colReference: string;
		colDesignation: string;
		colMarque: string;
		colCategorie: string;
		colPrixAchat: string;
		colPrixVente: string;
		colQuantite: string;
		colTypeRemise: string;
		colRemise: string;
	};
	monthlyObjectives: {
		updateSuccess: string;
		createSuccess: string;
		updateError: string;
		createError: string;
		fieldCA: string;
		fieldFactures: string;
		fieldConversion: string;
		fieldGlobalError: string;
		fieldCALabel: string;
		fieldCAEurLabel: string;
		fieldCAUsdLabel: string;
		fieldFacturesLabel: string;
		fieldConversionLabel: string;
		createBtn: string;
		pageTitle: string;
		title: string;
	};
	addArticleModal: {
		title: string;
		statusHeader: string;
		statusExisting: string;
		statusNew: string;
		typeLabel: string;
		colReference: string;
		colDesignation: string;
		colMarque: string;
		colCategorie: string;
		colUnite: string;
		colEmplacement: string;
		colPrixAchat: string;
		colPrixVente: string;
		colQuantite: string;
		colTypeRemise: string;
		colRemise: string;
		cancelBtn: string;
		addBtn: (n: number) => string;
	};
	globalRemiseModal: {
		title: string;
		typeLabel: string;
		typeNone: string;
		typePercent: string;
		typeFixed: (devise: string) => string;
		valuePercentLabel: string;
		valueAmountLabel: (devise: string) => string;
		helperPercent: string;
		helperAmount: string;
		errorMin: string;
		errorPercentRange: string;
		cancelBtn: string;
		applyBtn: string;
	};
	totalsCard: {
		totalHT: string;
		totalTVA: string;
		totalTTC: string;
		totalTTCApresRemise: string;
	};
	noPermission: {
		title: string;
		description: string;
	};
	maintenance: {
		logoAlt: string;
		chipLabel: string;
		title: string;
		description: string;
		suspended: string;
		comeBack: string;
	};
	addEntityModal: {
		title: (label: string) => string;
		fieldLabel: (label: string) => string;
		requiredError: (label: string) => string;
		addError: (label: string) => string;
		cancelBtn: string;
		addBtn: string;
	};
	notFound: {
		title: string;
		message: string;
		backBtn: string;
		homeBtn: string;
	};
	filterPanel: {
		and: string;
		or: string;
	};
	dateRange: {
		from: string;
		to: string;
	};
	managedByTable: {
		actions: string;
		you: string;
		role: string;
	};
	auth: {
		login: string;
		emailLabel: string;
		emailPlaceholder: string;
		passwordLabel: string;
		passwordPlaceholder: string;
		confirmPasswordLabel: string;
		confirmPasswordPlaceholder: string;
		forgotPassword: string;
		loginButton: string;
		recoveryTitle: string;
		recoverySubtitle: string;
		recoveryDescription: string;
		sendCodeButton: string;
		backToLogin: string;
		newPasswordTitle: string;
		newPasswordSubtitle: string;
		changePasswordButton: string;
		serviceUnavailable: string;
		enterCodeTitle: string;
		confirmCode: string;
		resendCode: string;
		passwordChanged: string;
		passwordChangedSub: string;
		codeSent: string;
		codeSendError: string;
		codeSentTo: string;
	};
};
